"""Render a human-readable Markdown report from the comparison log.

Aggregates across every judged query to answer the standing question: overall,
where does Fenzo win and where does it fall short versus each other model?
"""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .comparator import Comparison


def _fmt_list(items: list[str], limit: int = 8) -> str:
    if not items:
        return "_none recorded_"
    shown = items[:limit]
    return "\n".join(f"- {x}" for x in shown)


def build_markdown(comparisons: list[Comparison], subject: str) -> str:
    lines: list[str] = []
    lines.append(f"# Fenzo response comparison report")
    lines.append("")
    lines.append(f"_Generated {datetime.now(timezone.utc).isoformat()}_")
    lines.append(f"\nSubject under evaluation: **{subject}**")
    lines.append(f"\nQueries judged: **{len(comparisons)}**")

    # Aggregate: verdict tally, average score per model, subject win-rate.
    verdicts = Counter(c.subject_verdict for c in comparisons)
    scores_by_model: dict[str, list[float]] = defaultdict(list)
    subject_rank1 = 0
    all_strengths: list[str] = []
    all_weaknesses: list[str] = []
    for c in comparisons:
        for s in c.scores:
            scores_by_model[s.model].append(s.score)
            if s.model == subject and s.rank == 1:
                subject_rank1 += 1
        all_strengths.extend(c.subject_strengths)
        all_weaknesses.extend(c.subject_weaknesses)

    lines.append("\n## Summary")
    total = len(comparisons) or 1
    lines.append(
        f"\nFenzo verdict distribution — "
        f"better: {verdicts.get('better', 0)}, "
        f"comparable: {verdicts.get('comparable', 0)}, "
        f"worse: {verdicts.get('worse', 0)}."
    )
    lines.append(
        f"\nFenzo ranked #1 on **{subject_rank1}/{total}** "
        f"({100 * subject_rank1 / total:.0f}%) of queries."
    )

    lines.append("\n## Average judge score by model")
    lines.append("\n| Model | Avg score | Queries |")
    lines.append("| --- | --- | --- |")
    for model, vals in sorted(
        scores_by_model.items(), key=lambda kv: sum(kv[1]) / len(kv[1]), reverse=True
    ):
        marker = " ⬅ subject" if model == subject else ""
        lines.append(
            f"| {model}{marker} | {sum(vals) / len(vals):.2f} | {len(vals)} |"
        )

    lines.append("\n## Where Fenzo is strong (most cited strengths)")
    lines.append("")
    lines.append(_fmt_list([s for s, _ in Counter(all_strengths).most_common(8)]))

    lines.append("\n## Where Fenzo falls short (most cited weaknesses)")
    lines.append("")
    lines.append(_fmt_list([w for w, _ in Counter(all_weaknesses).most_common(8)]))

    lines.append("\n## Per-query detail")
    for c in comparisons:
        lines.append(f"\n### {c.query_id} — {c.subject_verdict.upper()}")
        lines.append(f"\n> {c.prompt}")
        lines.append(f"\n{c.summary}")
        lines.append("\n| Rank | Model | Score | Latency (s) | Chars |")
        lines.append("| --- | --- | --- | --- | --- |")
        for s in sorted(c.scores, key=lambda x: x.rank):
            marker = " ⬅" if s.model == subject else ""
            lines.append(
                f"| {s.rank} | {s.model}{marker} | {s.score:.1f} | "
                f"{s.latency_s:.2f} | {s.length_chars} |"
            )

    lines.append("\n---")
    lines.append("_Generated by the Fenzo benchmarker pipeline._")
    return "\n".join(lines) + "\n"


def write_report(
    comparisons: list[Comparison], subject: str, reports_dir: str | Path
) -> Path:
    d = Path(reports_dir)
    d.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out = d / f"report-{stamp}.md"
    out.write_text(build_markdown(comparisons, subject))
    return out
